version: 2
updates:
  - package-ecosystem: "npm"
    directory: "org.xtext.example.mydsl.vscode"
    schedule:
      interval: "weekly"
    groups:
      eslint-packages:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "*typescript-eslint*"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
