version: 2
updates:
  - package-ecosystem: "npm"
    directory: "org.xtext.example.mydsl.vscode"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
